version: '3.4'

services:
  webapplication3:
    image: ${DOCKER_REGISTRY-}webapplication3
    build:
      context: .
      dockerfile: WebApplication3/Dockerfile
    networks:
      - my_network
  SqlServerDb:
    user: root
    env_file:
      - .env.sample
    volumes:
      - ./dev_db_data:/var/opt/mssql/data
    container_name: SqlServerContainer
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 1435:1433
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P ${MSSQL_SA_PASSWORD} -Q 'SELECT 1' || exit 1"]
      interval: 10s
      retries: 10
      start_period: 30s
      timeout: 3s
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=qwerty!0
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
